apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: docker.io/envoyproxy
    chart: gateway-helm
    path: gateway-helm
    targetRevision: v0.0.0-latest
    helm:
      valuesObject:
        certgen:
          rbac:
            annotations:
              argocd.argoproj.io/sync-wave: "-1"  # Ensure rbac is created before the certgen job. This is a workaround for https://github.com/envoyproxy/gateway/issues/5223
        deployment:
          envoyGateway:
            resources:
              limits:
                cpu: 700m
                memory: 256Mi
      valueFiles:
      - $values/envoy-gateway/values.yaml
  - repoURL: 'https://github.com/zhaohuabing/envoy-gateway-argocd.git'
    ref: values
  destination:
    namespace: envoy-gateway-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
